name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild build \
            -project Xcodes.xcodeproj \
            -scheme Xcodes \
            -destination 'platform=macOS' \
            -skipPackagePluginValidation \
            CODE_SIGNING_ALLOWED=NO \
            | tail -20
